export { default as home } from './home.vue'
export { default as out } from './out.vue'
export { default as photo } from './photo.vue'
export { default as triangle } from './triangle.vue'
export { default as star } from './star.vue'
export { default as fork } from './fork.vue'
